// ─────────────────────────────────────────────────────────
// Seeds starter user accounts and the initial work orders.
// Run with:  npm run seed
//
// It reads the four starter passwords from environment variables
// so real passwords are never written into this file:
//   SEED_ADMIN_PW, SEED_ENGINEER_PW, SEED_QUALITY_PW, SEED_OPERATOR_PW
// If a variable is missing, that account is skipped with a warning.
// Safe to run more than once (ON CONFLICT DO NOTHING).
// ─────────────────────────────────────────────────────────
require('dotenv').config();
const bcrypt = require('bcryptjs');
const pool = require('./pool');

const cloneOps = (states) => {
  // Mirrors the frontend's 11-operation default routing so seeded WOs
  // look identical to what you see today. States is an array of statuses.
  const base = [
    { seq: '05',  name: 'Mould preparation',    type: 'prep' },
    { seq: '10',  name: 'Laminating',           type: 'laminating' },
    { seq: '20',  name: 'De-bulk #1',           type: 'debulk' },
    { seq: '30',  name: 'Laminating (cont.)',   type: 'laminating' },
    { seq: '40',  name: 'De-bulk #2',           type: 'debulk' },
    { seq: '150-QG', name: 'QG — Pre-cure',     type: 'quality-gate' },
    { seq: '150', name: 'Curing',               type: 'curing' },
    { seq: '160-QG', name: 'QG — Final',        type: 'quality-gate' },
    { seq: '160', name: 'Trimming',             type: 'trimming' },
    { seq: 'INS', name: 'Inspection',           type: 'inspection' },
    { seq: 'H&S', name: 'Safety sign-off',      type: 'safety' },
  ];
  return base.map((op, i) => ({
    id: i + 1, ...op, dur: 60, hazmat: false,
    status: states[i] || 'pending', steps: [], mats: [], media: [],
  }));
};

const WOS = [
  { id:'WO-2024-001', component:'Fwd Fuel Tank Bulkhead', part_no:'362-12120', elbit_pn:'54-10-00560-00', drawing_no:'54-DP-000675', batch_no:'B-2024-FTB-001', rev:'—', status:'in-progress', start_date:'2024-06-10', priority:'high', assigned_to:['A. Lima','T. Ribeiro'], hazmat:true, notes:'Resins — gloves mandatory at all times. PPE per H&S sheet p.3.', ops:cloneOps(['done','done','done','done','in-progress','pending','pending','pending','pending','pending','pending']) },
  { id:'WO-2024-002', component:'Aft Fuselage Skin Panel', part_no:'362-14200', elbit_pn:'54-10-00581-00', drawing_no:'54-DP-000681', batch_no:'B-2024-AFS-002', rev:'A', status:'in-progress', start_date:'2024-06-11', priority:'high', assigned_to:['M. Santos'], hazmat:true, notes:'Check fibre direction carefully — asymmetric layup.', ops:cloneOps(['done','done','in-progress','pending','pending','pending','pending','pending','pending','pending','pending']) },
  { id:'WO-2024-003', component:'Main Spar Web — Centre Section', part_no:'362-15010', elbit_pn:'54-10-00590-00', drawing_no:'54-DP-000695', batch_no:'B-2024-MSW-003', rev:'B', status:'quality-hold', start_date:'2024-06-09', priority:'critical', assigned_to:['C. Neves','R. Alves'], hazmat:true, notes:'Critical primary structure — 100% inspection required.', ops:cloneOps(['done','done','done','done','done','done','quality-hold','pending','pending','pending','pending']) },
  { id:'WO-2024-004', component:'Rudder Trailing Edge', part_no:'362-16400', elbit_pn:'54-10-00602-00', drawing_no:'54-DP-000710', batch_no:'B-2024-RTE-004', rev:'—', status:'complete', start_date:'2024-06-07', priority:'normal', assigned_to:['P. Mota'], hazmat:false, notes:'', ops:cloneOps(['done','done','done','done','done','done','done','done','done','done','done']) },
  { id:'WO-2024-005', component:'Elevator Skin — Upper', part_no:'362-17100', elbit_pn:'54-10-00615-00', drawing_no:'54-DP-000722', batch_no:'B-2024-ESU-005', rev:'A', status:'pending', start_date:'2024-06-13', priority:'normal', assigned_to:[], hazmat:false, notes:'Awaiting mould release from WO-2024-004.', ops:cloneOps([]) },
  { id:'WO-2024-006', component:'Wing Root Rib No.3', part_no:'362-18050', elbit_pn:'54-10-00627-00', drawing_no:'54-DP-000735', batch_no:'B-2024-WRR-006', rev:'—', status:'pending', start_date:'2024-06-14', priority:'low', assigned_to:[], hazmat:false, notes:'', ops:cloneOps([]) },
];

// Controlled documents seeded into the Document Pyramid register — mirrors
// the set the frontend used to keep in a client-only mock array.
const DOCS = [
  // QM — Quality Manual
  {id:'QD-001',ref:'QD-001',level:'QM',category:'manual',title:'Quality Management Manual',rev:'R03',status:'approved',date:'2025-01-15',owner:'QMS_MR',standard:'AS9100D §4',retention:'LOC',description:'Entry point of the QMS. Describes scope, processes, responsibilities and authorities across the INFURCI organisation.',applicability:'All INFURCI personnel and activities',writer:'QMS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'A. Monkari',date:'2025-01-14'},checker:{signed:true,name:'M. Laduron',date:'2025-01-14'},approver:{signed:true,name:'K. Vandierendonck',date:'2025-01-15'}},revHistory:[{rev:'R00',date:'2019-06-01',editor:'QMS_MR',object:'Initial issue'},{rev:'R01',date:'2020-11-10',editor:'QMS_MR',object:'Scope update'},{rev:'R02',date:'2022-05-14',editor:'QMS_MR',object:'AS9100D Rev D alignment'},{rev:'R03',date:'2025-01-15',editor:'QMS_MR',object:'Complete overhaul — EASA Part-21 addition'}],tags:['QMS','Manual'],format:'PDF / SharePoint',language:'English',linkedDocs:['QD-002','M02-01']},
  {id:'QD-002',ref:'QD-002',level:'QM',category:'manual',title:'Design Organisation Interface Document (DOID)',rev:'R01',status:'approved',date:'2024-11-01',owner:'DES_DR',standard:'AS9100D §8.3',retention:'LOC',description:'Defines the interface between the Design Organisation and the Production Organisation, including responsibilities for design verification and release.',applicability:'Design and Production departments',writer:'DES_DR',checker:'QMS_MR',approver:'HDO',approvals:{writer:{signed:true,name:'R. Pellin',date:'2024-10-30'},checker:{signed:true,name:'QMS_MR',date:'2024-10-31'},approver:{signed:true,name:'HDO',date:'2024-11-01'}},revHistory:[{rev:'R00',date:'2023-03-01',editor:'DES_DR',object:'Initial issue'},{rev:'R01',date:'2024-11-01',editor:'DES_DR',object:'DOA scope update — EASA.21J.678 reference added'}],tags:['DOA','Design','Interface'],format:'PDF / SharePoint',language:'English',linkedDocs:['QD-001']},
  // H4 — Procedures
  {id:'M02-01',ref:'M02-02-04-01',level:'H4',category:'procedures',title:'Organisation and Management of Documentation',rev:'R09',status:'approved',date:'2025-01-07',owner:'QLT_QMS_MR',standard:'AS9100D §7.5',retention:'6 YRS',description:'Defines the management rules for creation, approval, modification, and archiving of all documents in the SABCA/INFURCI document system. Covers document pyramid H1–H6, numbering, approval chain, diffusion, archiving, and destruction.',applicability:'All document creators — Quality, POW, PKU, Program Teams',writer:'QLT_QMS_MR',checker:'AFS_ICT_MR',approver:'M02-POW-TM',approvals:{writer:{signed:true,name:'Asmaa Monkari',date:'2025-01-07'},checker:{signed:true,name:'Miguel Laduron',date:'2025-01-07'},approver:{signed:true,name:'Kristine Vandierendonck',date:'2025-01-07'}},revHistory:[{rev:'R00',date:'2019-11-06',editor:'A. Monkari',object:'Creation — replaces MG-000-00, IQ40501, IQ40502, IQ41601'},{rev:'R05',date:'2022-03-11',editor:'A. Monkari',object:'PART21J removed; level 6 added; template nomenclatures updated'},{rev:'R06',date:'2022-11-28',editor:'A. Monkari',object:'Complete overhaul'},{rev:'R09',date:'2025-01-07',editor:'H. Cox',object:'§6.8.5 Archiving in IQSMS; SW End-of-subscription; Part 21G SMS'}],tags:['Documentation','Control'],format:'PDF / SharePoint',language:'English',linkedDocs:['QD-001']},
  {id:'M02-02',ref:'M02-04-02-01',level:'H4',category:'procedures',title:'Control of Nonconforming Outputs',rev:'R05',status:'approved',date:'2024-09-12',owner:'QLT_QMS_TM',standard:'AS9100D §8.7',retention:'LOP+6 YRS',description:'Procedure for identification, segregation, disposition and records of nonconforming products and services.',applicability:'Production, Quality, Inspection',writer:'QLT_QMS_TM',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_TM',date:'2024-09-10'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-09-11'},approver:{signed:true,name:'QLT_DR',date:'2024-09-12'}},revHistory:[{rev:'R00',date:'2019-01-10',editor:'QLT_QMS_TM',object:'Initial issue'},{rev:'R05',date:'2024-09-12',editor:'QLT_QMS_TM',object:'RDR workflow updated; IQSMS link added'}],tags:['NCR','Nonconformance'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01']},
  {id:'M02-03',ref:'C03-06-04-01',level:'H4',category:'procedures',title:'Program and Technical Documentation Management',rev:'R02',status:'approved',date:'2024-06-01',owner:'DCC_MR',standard:'AS9100D §7.5',retention:'LOP+6 YRS',description:'Defines rules for managing program-level and technical documents including MT, FT, TH and program-specific documents.',applicability:'Engineering, DCC, Program Teams',writer:'DCC_MR',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'DCC_MR',date:'2024-05-30'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-05-31'},approver:{signed:true,name:'QLT_DR',date:'2024-06-01'}},revHistory:[{rev:'R00',date:'2021-03-01',editor:'DCC_MR',object:'Initial issue'},{rev:'R02',date:'2024-06-01',editor:'DCC_MR',object:'Alignment with VMP-001-002 and DOA process map'}],tags:['Documentation','Program','Technical'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01','QD-002']},
  {id:'M02-04',ref:'M02-02-05-01',level:'H4',category:'procedures',title:'Internal Audit Procedure',rev:'R04',status:'approved',date:'2024-03-20',owner:'QLT_QMS_MR',standard:'AS9100D §9.2',retention:'7 YRS',description:'Defines the planning, execution, reporting and follow-up of internal quality audits across all QMS processes.',applicability:'Internal audit function, process owners',writer:'QLT_QMS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_MR',date:'2024-03-18'},checker:{signed:true,name:'QLT_QMS_TM',date:'2024-03-19'},approver:{signed:true,name:'QLT_DR',date:'2024-03-20'}},revHistory:[{rev:'R00',date:'2020-02-01',editor:'QLT_QMS_MR',object:'Initial issue'},{rev:'R04',date:'2024-03-20',editor:'QLT_QMS_MR',object:'Updated audit scope for EASA Part-21 surveillance'}],tags:['Audit'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01']},
  {id:'M02-05',ref:'M02-02-06-01',level:'H4',category:'procedures',title:'Corrective and Preventive Actions (CAPA)',rev:'R06',status:'approved',date:'2024-07-08',owner:'QLT_QMS_MR',standard:'AS9100D §10.2',retention:'7 YRS',description:'Defines the process for root cause analysis, corrective action, preventive action, and effectiveness verification.',applicability:'All departments — any person can initiate a CAPA',writer:'QLT_QMS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_MR',date:'2024-07-06'},checker:{signed:true,name:'QLT_QMS_TM',date:'2024-07-07'},approver:{signed:true,name:'QLT_DR',date:'2024-07-08'}},revHistory:[{rev:'R00',date:'2019-03-15',editor:'QLT_QMS_MR',object:'Initial issue'},{rev:'R06',date:'2024-07-08',editor:'QLT_QMS_MR',object:'Process updated; IQSMS integration for CA tracking'}],tags:['CAPA','Corrective','Preventive'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01','M02-04']},
  {id:'M02-06',ref:'C08-01-01-01',level:'H4',category:'procedures',title:'Supplier Qualification and Evaluation',rev:'R03',status:'approved',date:'2024-10-15',owner:'PUR_MR',standard:'AS9100D §8.4',retention:'LOP+6 YRS',description:'Defines supplier qualification, ASL management, supplier audit, supplier NCR, and SQA via Quality Plan.',applicability:'Procurement, Supplier Quality Assurance',writer:'PUR_MR',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'PUR_MR',date:'2024-10-13'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-10-14'},approver:{signed:true,name:'QLT_DR',date:'2024-10-15'}},revHistory:[{rev:'R00',date:'2021-05-01',editor:'PUR_MR',object:'Initial issue'},{rev:'R03',date:'2024-10-15',editor:'PUR_MR',object:'Tier-1/Tier-2 distinction clarified; archiving per §6.8.8 added'}],tags:['Supplier','ASL','SQA'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01']},
  {id:'M02-07',ref:'S02-02-01-01',level:'H4',category:'procedures',title:'Training, Competence and Qualification',rev:'R02',status:'approved',date:'2024-05-30',owner:'HR_DR',standard:'AS9100D §7.2',retention:'3 YRS post-departure',description:'Defines training needs identification, qualification requirements, competence matrix, and record management for all personnel.',applicability:'All departments',writer:'HR_DR',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'HR_DR',date:'2024-05-28'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-05-29'},approver:{signed:true,name:'QLT_DR',date:'2024-05-30'}},revHistory:[{rev:'R00',date:'2021-09-01',editor:'HR_DR',object:'Initial issue'},{rev:'R02',date:'2024-05-30',editor:'HR_DR',object:'LMS integration; certification expiry alerts added'}],tags:['Training','Competence','HR'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01']},
  {id:'M02-08',ref:'S04-01-01-01',level:'H4',category:'procedures',title:'Control of Monitoring and Measurement Equipment',rev:'R04',status:'in-review',date:'2025-02-01',owner:'LAB_MR',standard:'AS9100D §7.1.5',retention:'LOP+6 YRS',description:'Defines calibration planning, instrument register, calibration status marking, and action required when equipment is found out of calibration.',applicability:'All measurement and test equipment users',writer:'LAB_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'LAB_MR',date:'2025-01-30'},checker:{signed:false,name:'',date:''},approver:{signed:false,name:'',date:''}},revHistory:[{rev:'R00',date:'2020-04-01',editor:'LAB_MR',object:'Initial issue'},{rev:'R04',date:'2025-02-01',editor:'LAB_MR',object:'MES calibration alert integration; NADCAP scope expanded — IN REVIEW'}],tags:['Calibration','Measurement'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-01']},
  // H5 — Instructions
  {id:'I-001',ref:'VMI-QA-001',level:'H5',category:'instructions',title:'First Article Inspection (FAI) Instruction',rev:'A01',status:'approved',date:'2024-04-10',owner:'QLT_QMS_TM',standard:'AS9100D §8.5',retention:'LOP+6 YRS',description:'Step-by-step instruction for planning and conducting First Article Inspections per AS9102 requirements.',applicability:'Quality Engineering, Production',writer:'QLT_QMS_TM',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_TM',date:'2024-04-09'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-04-09'},approver:{signed:true,name:'QLT_DR',date:'2024-04-10'}},revHistory:[{rev:'A00',date:'2023-01-15',editor:'QLT_QMS_TM',object:'Initial issue'},{rev:'A01',date:'2024-04-10',editor:'QLT_QMS_TM',object:'AS9102 Rev C alignment; balloon drawing requirements added'}],tags:['FAI','Inspection'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-02']},
  {id:'I-002',ref:'VMI-QA-002',level:'H5',category:'instructions',title:'In-Process Inspection Record — Composites',rev:'A02',status:'approved',date:'2024-04-18',owner:'QLT_QMS_TM',standard:'AS9100D §8.5',retention:'LOP+6 YRS',description:'Worksheet for recording in-process inspection checkpoints during composite manufacturing operations.',applicability:'Quality Control, Production — Composites',writer:'QLT_QMS_TM',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_TM',date:'2024-04-17'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-04-18'},approver:{signed:true,name:'QLT_DR',date:'2024-04-18'}},revHistory:[{rev:'A00',date:'2023-06-01',editor:'QLT_QMS_TM',object:'Initial issue'},{rev:'A02',date:'2024-04-18',editor:'QLT_QMS_TM',object:'Out-time log column added; autoclave cycle reference added'}],tags:['Composites','Inspection','In-process'],format:'PDF / SharePoint',language:'English',linkedDocs:['I-005']},
  {id:'I-003',ref:'VMI-QA-003',level:'H5',category:'instructions',title:'Receiving Inspection Instruction',rev:'A00',status:'approved',date:'2023-11-05',owner:'ASI_MR',standard:'AS9100D §8.4',retention:'LOP+6 YRS',description:'Instruction for incoming material and component inspection including certificate review and dimensional checks.',applicability:'Receiving, Quality Inspection',writer:'ASI_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'ASI_MR',date:'2023-11-04'},checker:{signed:true,name:'QLT_QMS_TM',date:'2023-11-05'},approver:{signed:true,name:'QLT_DR',date:'2023-11-05'}},revHistory:[{rev:'A00',date:'2023-11-05',editor:'ASI_MR',object:'Initial issue'}],tags:['Receiving','Inspection','Incoming'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-06']},
  {id:'I-004',ref:'VMI-QA-004',level:'H5',category:'instructions',title:'RDR / Deviation Request Completion Guide',rev:'A03',status:'approved',date:'2024-08-22',owner:'QLT_QMS_TM',standard:'AS9100D §8.7',retention:'LOP+6 YRS',description:'Guide for completing, routing and closing Rejection / Deviation Reports including MRB submission.',applicability:'Quality Engineering, Production, QC',writer:'QLT_QMS_TM',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QLT_QMS_TM',date:'2024-08-20'},checker:{signed:true,name:'QLT_QMS_MR',date:'2024-08-21'},approver:{signed:true,name:'QLT_DR',date:'2024-08-22'}},revHistory:[{rev:'A00',date:'2022-01-10',editor:'QLT_QMS_TM',object:'Initial issue'},{rev:'A03',date:'2024-08-22',editor:'QLT_QMS_TM',object:'IQSMS auto-notification step added; Permit for Alternative procedure'}],tags:['RDR','NCR','Deviation'],format:'PDF / SharePoint',language:'English',linkedDocs:['M02-02']},
  {id:'I-005',ref:'VMI-QA-005',level:'H5',category:'instructions',title:'Out-time and Cold-storage Monitoring Worksheet',rev:'A01',status:'approved',date:'2024-01-09',owner:'QCS_MR',standard:'NADCAP',retention:'LOP+6 YRS',description:'Log sheet for tracking prepreg and adhesive out-time accumulation and cold-storage intervals against material batch limits.',applicability:'Composites shop — laminating operators',writer:'QCS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'QCS_MR',date:'2024-01-08'},checker:{signed:true,name:'QLT_QMS_TM',date:'2024-01-08'},approver:{signed:true,name:'QLT_DR',date:'2024-01-09'}},revHistory:[{rev:'A00',date:'2023-02-01',editor:'QCS_MR',object:'Initial issue'},{rev:'A01',date:'2024-01-09',editor:'QCS_MR',object:'Thaw time tracking column added; batch card link added'}],tags:['Composites','Out-time','NADCAP'],format:'PDF / SharePoint',language:'Dutch / English',linkedDocs:['I-002']},
  {id:'I-006',ref:'VMI-QA-006',level:'H5',category:'instructions',title:'Autoclave Cycle Log — Composites',rev:'A02',status:'draft',date:'2025-03-10',owner:'QCS_MR',standard:'NADCAP / AS9100D',retention:'LOP+6 YRS',description:'Cycle record for each autoclave run including ramp rates, dwell time, pressure, thermocouple data and operator sign-off.',applicability:'Autoclave operators, Quality',writer:'QCS_MR',checker:'',approver:'',approvals:{writer:{signed:false,name:'',date:''},checker:{signed:false,name:'',date:''},approver:{signed:false,name:'',date:''}},revHistory:[{rev:'A00',date:'2023-08-01',editor:'QCS_MR',object:'Initial issue'},{rev:'A01',date:'2024-05-20',editor:'QCS_MR',object:'Thermocouple map reference added'},{rev:'A02',date:'2025-03-10',editor:'QCS_MR',object:'DRAFT — calibration cert link and lot traceability field — pending review'}],tags:['Autoclave','NADCAP','Composites'],format:'PDF / SharePoint',language:'English',linkedDocs:['I-005','I-002']},
  // REC — Records
  {id:'R-001',ref:'FRM-QA-001',level:'REC',category:'records',title:'Route Sheet / Manufacturing Dossier',status:'active',rev:'—',date:'—',owner:'Production',standard:'AS9100D §8.5',retention:'LOP+6 YRS',description:'Paper/electronic dossier accompanying each work order through production. Contains all operational sign-offs, inspection stamps, out-time logs, and final acceptance signature.',applicability:'All production work orders',writer:'Production',checker:'QCS',approver:'QC',approvals:{writer:{signed:true,name:'(per WO)',date:'(per WO)'},checker:{signed:true,name:'(per WO)',date:'(per WO)'},approver:{signed:true,name:'(per WO)',date:'(per WO)'}},revHistory:[],tags:['Record','Production','Traceability'],format:'Paper / S4Hana',language:'Language of the user',linkedDocs:['I-002','I-005']},
  {id:'R-002',ref:'FRM-QA-002',level:'REC',category:'records',title:'Non-Conformance Report (RDR)',status:'active',rev:'—',date:'—',owner:'Quality Control',standard:'AS9100D §8.7',retention:'LOP+6 YRS',description:'Form for recording, routing, and closing nonconformances. Includes MRB disposition fields and IQSMS reference.',applicability:'Quality Control, Production, QE',writer:'QC',checker:'QE',approver:'QM',approvals:{writer:{signed:true,name:'(per NCR)',date:'(per NCR)'},checker:{signed:true,name:'(per NCR)',date:'(per NCR)'},approver:{signed:true,name:'(per NCR)',date:'(per NCR)'}},revHistory:[],tags:['Record','NCR','RDR'],format:'Paper / S4Hana',language:'Language of the user',linkedDocs:['M02-02','I-004']},
  {id:'R-003',ref:'FRM-QA-003',level:'REC',category:'records',title:'CAPA Register',status:'active',rev:'—',date:'—',owner:'QMS_MR',standard:'AS9100D §10.2',retention:'7 YRS',description:'Electronic register of all corrective and preventive actions. Fields: ID, NCR source, type, title, root cause, actions, owner, target date, status, effectiveness review.',applicability:'Quality Management',writer:'QMS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'(per entry)',date:'(per entry)'},checker:{signed:true,name:'(per entry)',date:'(per entry)'},approver:{signed:true,name:'(per entry)',date:'(per entry)'}},revHistory:[],tags:['Record','CAPA'],format:'Electronic / SharePoint',language:'English',linkedDocs:['M02-05']},
  {id:'R-004',ref:'FRM-QA-004',level:'REC',category:'records',title:'Calibration Certificate Register',status:'active',rev:'—',date:'—',owner:'LAB_MR',standard:'AS9100D §7.1.5',retention:'LOP+6 YRS',description:'Instrument register tracking calibration intervals, last/next dates, laboratory, certificate reference, and status.',applicability:'All measurement and test equipment',writer:'LAB_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'(per entry)',date:'(per entry)'},checker:{signed:true,name:'(per entry)',date:'(per entry)'},approver:{signed:true,name:'(per entry)',date:'(per entry)'}},revHistory:[],tags:['Record','Calibration'],format:'Electronic / LAB',language:'English',linkedDocs:['M02-08']},
  {id:'R-005',ref:'FRM-QA-005',level:'REC',category:'records',title:'Internal Audit Report',status:'active',rev:'—',date:'—',owner:'QMS_MR',standard:'AS9100D §9.2',retention:'7 YRS',description:'Standardised audit report capturing scope, criteria, method, team, findings (with category), observations, and agreed CAPAs.',applicability:'Internal audit function',writer:'Audit Lead',checker:'QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'(per audit)',date:'(per audit)'},checker:{signed:true,name:'(per audit)',date:'(per audit)'},approver:{signed:true,name:'(per audit)',date:'(per audit)'}},revHistory:[],tags:['Record','Audit'],format:'Electronic / IQSMS',language:'English',linkedDocs:['M02-04']},
  {id:'R-006',ref:'FRM-QA-006',level:'REC',category:'records',title:'Training Record / Individual Qualification Dossier',status:'active',rev:'—',date:'—',owner:'HR_DR',standard:'AS9100D §7.2',retention:'Permanent',description:'Individual file per employee containing qualifications held, certification dates, training records, and competence assessment results.',applicability:'All personnel',writer:'HR_DR',checker:'Line Manager',approver:'HR_DR',approvals:{writer:{signed:true,name:'(per person)',date:'(per person)'},checker:{signed:true,name:'(per person)',date:'(per person)'},approver:{signed:true,name:'(per person)',date:'(per person)'}},revHistory:[],tags:['Record','Training','Competence'],format:'Paper / LMS',language:'Language of the user',linkedDocs:['M02-07']},
  {id:'R-007',ref:'FRM-QA-007',level:'REC',category:'records',title:'Supplier Audit Report',status:'active',rev:'—',date:'—',owner:'PUR_MR',standard:'AS9100D §8.4',retention:'9 YRS',description:'Supplier audit findings report including pre-audit questionnaire results, on-site findings, corrective action requests, and follow-up closure.',applicability:'Supplier Quality Assurance',writer:'PUR_MR / SQA',checker:'QLT_QMS_MR',approver:'QLT_DR',approvals:{writer:{signed:true,name:'(per audit)',date:'(per audit)'},checker:{signed:true,name:'(per audit)',date:'(per audit)'},approver:{signed:true,name:'(per audit)',date:'(per audit)'}},revHistory:[],tags:['Record','Supplier','Audit'],format:'Electronic',language:'English',linkedDocs:['M02-06']},
  {id:'R-008',ref:'FRM-QA-008',level:'REC',category:'records',title:'Management Review Minutes',status:'active',rev:'—',date:'—',owner:'QLT_DR',standard:'AS9100D §9.3',retention:'6 YRS',description:'Minutes of the annual management review covering QMS performance, audit results, CAPAs, customer feedback, and improvement objectives.',applicability:'Top management, QMS_MR',writer:'QMS_MR',checker:'QLT_QMS_TM',approver:'QLT_DR',approvals:{writer:{signed:true,name:'(per meeting)',date:'(per meeting)'},checker:{signed:true,name:'(per meeting)',date:'(per meeting)'},approver:{signed:true,name:'(per meeting)',date:'(per meeting)'}},revHistory:[],tags:['Record','Management Review'],format:'Electronic / SharePoint',language:'English',linkedDocs:['M02-04','M02-05']},
];

const STARTER_USERS = [
  { username:'admin',    full_name:'System Administrator', role:'admin',    envKey:'SEED_ADMIN_PW' },
  { username:'engineer', full_name:'Engineering',          role:'engineer', envKey:'SEED_ENGINEER_PW' },
  { username:'quality',  full_name:'Quality',              role:'quality',  envKey:'SEED_QUALITY_PW' },
  { username:'operator', full_name:'Shop-floor Operator',  role:'operator', envKey:'SEED_OPERATOR_PW' },
];

(async () => {
  try {
    // Users
    for (const u of STARTER_USERS) {
      const pw = process.env[u.envKey];
      if (!pw) { console.warn(`⚠ Skipping "${u.username}" — ${u.envKey} not set.`); continue; }
      const hash = await bcrypt.hash(pw, 12);
      await pool.query(
        `INSERT INTO users (username, full_name, role, password_hash)
         VALUES ($1,$2,$3,$4)
         ON CONFLICT (username) DO NOTHING`,
        [u.username, u.full_name, u.role, hash]
      );
      console.log(`✓ User ready: ${u.username} (${u.role})`);
    }

    // Work orders
    for (const w of WOS) {
      await pool.query(
        `INSERT INTO work_orders
           (id, component, part_no, elbit_pn, drawing_no, batch_no, rev,
            status, priority, start_date, assigned_to, hazmat, notes, ops)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
         ON CONFLICT (id) DO NOTHING`,
        [w.id, w.component, w.part_no, w.elbit_pn, w.drawing_no, w.batch_no, w.rev,
         w.status, w.priority, w.start_date, JSON.stringify(w.assigned_to),
         w.hazmat, w.notes, JSON.stringify(w.ops)]
      );
    }
    console.log(`✓ Seeded ${WOS.length} work orders.`);

    // Controlled documents
    for (const d of DOCS) {
      await pool.query(
        `INSERT INTO controlled_documents
           (id, ref, level, category, title, rev, status, doc_date, owner, standard, retention,
            description, applicability, writer, checker, approver, approvals, rev_history, tags,
            format, language, linked_docs)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
         ON CONFLICT (id) DO NOTHING`,
        [d.id, d.ref, d.level, d.category, d.title, d.rev, d.status, d.date, d.owner, d.standard,
         d.retention, d.description, d.applicability, d.writer, d.checker, d.approver,
         JSON.stringify(d.approvals || {}), JSON.stringify(d.revHistory || []), JSON.stringify(d.tags || []),
         d.format, d.language, JSON.stringify(d.linkedDocs || [])]
      );
    }
    console.log(`✓ Seeded ${DOCS.length} controlled documents.`);
    console.log('\nDone. You can now start the server.');
  } catch (err) {
    console.error('✗ Seed failed:', err.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
})();
